name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip
    
    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        ARM_SUBSCRIPTION_ID: "1eb5e572-df10-47a3-977e-b0ec272641e4"
        ARM_TENANT_ID: "96bc4f68-3e74-42fe-ad32-c2626f49557f"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.terraform.outputs.webapp_name }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
    
    - name: Run Database Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ steps.terraform.outputs.mysql_host }}
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: ${{ steps.terraform.outputs.mysql_username }}
        DB_PASSWORD: ${{ steps.terraform.outputs.mysql_password }}
      run: |
        php artisan migrate --force 