name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/laravel-app:${{ github.sha }}
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
        -var="docker_image=${{ secrets.REGISTRY_LOGIN_SERVER }}/laravel-app:${{ github.sha }}" \
        -var="docker_registry_url=${{ secrets.REGISTRY_LOGIN_SERVER }}" \
        -var="docker_registry_username=${{ secrets.REGISTRY_USERNAME }}" \
        -var="docker_registry_password=${{ secrets.REGISTRY_PASSWORD }}"

    - name: Generate .env file
      run: |
        php artisan key:generate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache 